#!/usr/bin/env ruby

begin
  require 'pry'
  Pry.start
  exit
rescue LoadError
  $stderr.puts 'Pry is not available. Continuing with good old IRB.'
end

def quick(repetitions = 100, &block)
  require 'benchmark'
  Benchmark.bmbm do |b|
    b.report { repetitions.times(&block) }
  end
  nil
end

alias_method :q, :exit

begin
  load File.expand_path('~/.railsrc') if defined?(Rails) && Rails.env
rescue LoadError
end
