---
- name: Install Erlang
  homebrew: name=erlang state=latest

- name: Install rebar
  homebrew: name=rebar state=head

- name: Link dotfiles
  file: src={{ item }} dest=~/.{{ item | basename }} state=link
  with_fileglob:
    - ./*
