---
- name: Create ~/.bin
  file: dest=~/.bin state=directory

- name: Link dotfiles
  file: src={{ item }} dest=~/.{{ item | basename }} state=link
  with_fileglob:
    - ./conf/*

- name: Link executables
  file: src={{ item }} dest=~/.bin/{{ item | basename }} state=link
  with_fileglob:
    - ./bin/*

- name: Compile Go binaries
  command: go build -o ~/.bin/{{ item | basename | regex_replace('\.go$', '') }} {{ item }}
  with_fileglob:
    - ./go/*
