---
- name: Create ~/.bin
  file: dest=~/.bin state=directory

# HACK: Ansible won't link relative files?!
# https://github.com/ansible/ansible/issues/7627
- name: Link lein
  file: src={{ item }} dest=~/.bin/{{ item | basename }} state=link
  with_fileglob:
    - ./lein*

- name: Create ~/.lein
  file: dest=~/.lein state=directory

- name: Link profiles.clj
  file: src={{ item }} dest=~/.lein/{{ item | basename }} state=link
  with_fileglob:
    - ./*

- name: Download boot.sh
  get_url: >-
    url=https://github.com/boot-clj/boot/releases/download/2.0.0-rc12/boot.sh
    sha256sum=5d4b417671277e1648495e9bbfd190486d410656b40401d05b2c44aebf0aeac8
    dest=/usr/local/bin/boot
    mode=0755
