---
- name: Create ~/.bin
  file: dest=~/.bin state=directory

- name: Install latest boot
  homebrew: name={{ item }} state=latest
  with_items:
    - boot-clj
    - leiningen
  tags: update

- name: Create ~/.lein
  file: dest=~/.lein state=directory

- name: Link profiles.clj
  file: src={{ item }} dest=~/.lein/{{ item | basename }} state=link
  with_fileglob:
    - ./*
