---
- name: Clone pyenv
  git: >
    repo=git://github.com/yyuu/pyenv.git
    dest=~/.pyenv
  tags: update

- name: Install Pythons
  shell: 'pyenv install --skip-existing {{ item }}'
  with_items: dotfiles.python.versions
  # TODO Improve change detection
  changed_when: no
