---
- name: Install git
  homebrew: name={{ item }} state=latest
  with_items:
    - gh
    - ghi
    - git
    - git-extras
  tags: update

- name: Link dotfiles
  file: src={{ item }} dest=~/.{{ item | basename }} state=link
  with_fileglob:
    - ./conf/*

- name: Create ~/.bin
  file: dest=~/.bin state=directory

- name: Link executables
  file: src={{ item }} dest=~/.bin/{{ item | basename }} state=link
  with_fileglob:
    - ./bin/*
