---
- name: Clone Emacs config
  git: >
    repo=git@github.com:jcf/emacs.d.git
    dest=~/.emacs.d
    force=no
  tags: update

# This ensures we get a recent version of Emacs on occassions where someone runs
# `emacs` directly. This is happens all the time with `cask exec`.
- name: Install Homebrew Emacs
  homebrew: name=emacs state=latest
  tags: update

# http://emacsformacosx.com/tips
- name: Install Emacs
  mac_pkg: >
    pkg_type=app
    url=http://emacsformacosx.com/emacs-builds/Emacs-24.4-universal.dmg
    archive_type=dmg archive_path=Emacs.app

- name: Update packages
  command: cask update chdir=~/.emacs.d
  tags: update

- name: Create ~/.bin
  file: dest=~/.bin state=directory

- name: Link emacsclient
  file: >
    src=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient
    dest=~/.bin/emacsclient
    state=link

# - name: Link launchd plist
#   file: >
#     src={{ item }}
#     dest=~/Library/LaunchAgents/{{ item | basename }}
#     state=link
#   with_fileglob:
#     - ./launchd/*.plist

- name: Link executables
  file: src={{ item }} dest=~/.bin/{{ item | basename }} state=link
  with_fileglob:
    - ./bin/*

# From http://stackoverflow.com/a/8920373/123142

# > You don't have eterm-color terminfo. You should create eterm-color terminfo
# > by using following command.
- name: Generate terminfo for better ZSH support
  command: >
    tic -o ~/.terminfo /Applications/Emacs.app/Contents/Resources/etc/e/eterm-color.ti

- name: Install GNU global
  homebrew: name=global install_options=with-exuberant-ctags
  tags: gtags

- name: Install pygments
  pip: name=pygments state=latest
  tags: gtags

- name: Clone global-pygments-plugin
  git: >
    repo=git://github.com/yoshizow/global-pygments-plugin.git
    dest=~/.cache/global-pygments-plugin
  tags: gtags

- name: Make global-pygments-plugin
  shell: >
    cd ~/.cache/global-pygments-plugin &&
    sh reconf.sh &&
    ./configure --prefix=/usr/local/bin --with-exuberant-ctags=/usr/local/bin/ctags &&
    make && make install
  # creates: /usr/local/etc/gtags.conf
  tags: gtags

- name: Download ycmd
  git: >-
    repo=git://github.com/Valloric/ycmd.git
    dest=~/.cache/ycmd
  tags: ycmd

- name: Build ycmd
  command: >-
    ./build.sh --clang-completer chdir=~/.cache/ycmd
  tags: ycmd
