---
- name: Install jenv
  git: >
    repo=git://github.com/gcuisinier/jenv.git
    dest=~/.jenv
  tags: update

- name: Install Java versions
  mac_pkg: >
    pkg_name=com.oracle.jdk{{ item.major }}u{{ item.minor }} pkg_version=1.1
    url=http://download.oracle.com/otn-pub/java/jdk/{{ item.major }}u{{ item.minor }}-{{ item.patch }}/jdk-{{ item.major }}u{{ item.minor }}-macosx-x64.dmg
    curl_opts="-L --cookie oraclelicense=accept-securebackup-cookie"
    archive_type=dmg archive_path='JDK {{ item.major }} Update {{ item.minor }}.pkg'
  sudo: yes
  with_items: dotfiles.jvm.versions

- name: Register all JVMs
  shell: 'jenv add {{ item }}/Contents/Home'
  with_fileglob:
    - /Library/Java/JavaVirtualMachines/*

- name: Set current JVM
  shell: 'jenv global {{ dotfiles.jvm.default_version }}'
  ignore_errors: yes
