---
- name: Clone ~/.js
  git: |
    repo=git@github.com:jcf/dotjs-scripts.git
    dest=~/.js
    force=no
  tags: update

- name: Update dotjs
  git: |
    repo=https://github.com/jcf/dotjs.git
    dest=~/.cache/dotjs
  tags: update

- name: Install dotjs
  command: |
    rake install:daemon install:agent
    chdir=~/.cache/dotjs
    creates=/usr/local/bin/djsd
