---
- name: Install goenv
  git: >-
    repo=git://github.com/wfarr/goenv.git
    dest=~/.goenv
  tags: update

- name: Create GOPATH
  file: dest={{ dotfiles.go.path }} state=directory

- name: Install Go version
  shell: 'goenv install {{ item }}'
  with_items: dotfiles.go.versions
  changed_when: no
  register: result
  failed_when: '"rmdir: /Users/jcf/.goenv/versions/{{ item }}: Directory not empty" not in result.stderr'

- name: Set default Go version
  shell: 'goenv global {{ dotfiles.go.default_version }}'

- name: Install packages
  environment:
    gopath: dotfiles.go.path
  shell: 'go get {{ item }}'
  with_items: dotfiles.go.packages
  # TODO Improve changed_when detection
  changed_when: no
