#!/usr/bin/env zsh
# Usage: dotfiles install
#
# Summary: Install packages and other dev dependencies
#
# Help: Checks for required external dependencies that are a pain to install
# automatically, and then install those dependencies that aren't.
set -e

dotfiles-packages
dotfiles-emacs
dotfiles-ruby
# dotfiles-go
dotfiles-python
dotfiles-haskell
dotfiles-heroku
