#!/usr/bin/env bash
set -e
export -n CDPATH

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${DOTFILES_ROOT}" ]; then
  DOTFILES_ROOT="${HOME}/.dotfiles"
else
  DOTFILES_ROOT="${DOTFILES_ROOT%/}"
fi
export DOTFILES_ROOT

if [ -z "${DOTFILES_DIR}" ]; then
  DOTFILES_DIR="$(pwd)"
else
  cd "$DOTFILES_DIR" 2>/dev/null || {
    echo "dotfiles: cannot change working directory to \`$DOTFILES_DIR'"
    exit 1
  } >&2
  DOTFILES_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export DOTFILES_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(dotfiles-help)" >&2
  ;;
* )
  command_path="$(command -v "dotfiles-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "dotfiles: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
