#!/usr/bin/env zsh
set -e

say() {
  echo "\e[33m=>\e[0m $@"
}

require() {
  type $x >/dev/null 2>&1 || {
    echo >&2 "dotfiles: $x not installed."; exit 1;
  }
}

require 'pyenv'

say "Installing missing Python versions..."

versions=('2.7.3' 'pypy-1.9')
installed=$(pyenv versions --bare)

for version in $versions; do
  if [[ -z $installed[(r)$version] ]]; then
    pyenv install $version
  fi
done
