#!/usr/bin/env zsh
set -e

say() {
  echo "\e[33m=>\e[0m $@"
}

require() {
  type $x >/dev/null 2>&1 || {
    echo >&2 "dotfiles: $x not installed."; exit 1;
  }
}

require 'go'

packages=(
  github.com/nsf/gocode)

say "Installing go packages..."

for package in $packages; do
  sudo go get $package
done
