#!/usr/bin/env zsh
# Usage: dotfiles link
#
# Summary: Link runcoms and `.symlink' files in to home folder
#
# Help: You should only need to run this once. It will skip any files that
# already exist.
set -e

link_dotfile() {
  local to="$1"
  local from="${1:t:s/\.symlink//}"

  cd $HOME
  ln -snf "$to" ".$from" 2>/dev/null || true
}

links=($HOME/.dotfiles/**/*.symlink(N))

for file in $links; do
  link_dotfile $file
done
