#!/usr/bin/env zsh
# Usage: dotfiles install
#
# Summary: Install packages and other dev dependencies
#
# Help: Checks for required external dependencies that are a pain to install
# automatically, and then install those dependencies that aren't.
#
# Install will check for Homebrew, and install the most basic of packages with
# it. It will then clone Vundle for Vim bundles, and 
set -e

dotfiles-packages
dotfiles-ruby
dotfiles-python
dotfiles-heroku
