#!/usr/bin/env zsh
set -e

say() {
  echo "\e[33m=>\e[0m $@"
}

brew_install() {
  brew install "$@" 2>/dev/null
}

git_clone() {
  [[ -d $2 ]] || { git clone $1 $2 &>/dev/null }
}

github_clone() {
  git_clone "git://github.com/$1.git" $2
}

say "Installing MacVim..."
brew_install "macvim" "--with-cscope --with-lua --override-system-vim --HEAD"

say "Cloning vim config..."
github_clone 'jcf/vimrc' $HOME/.vim

say "Installing neobundle..."
github_clone 'Shougo/neobundle.vim' $HOME/.vim/bundle/neobundle.vim
