#!/usr/bin/env zsh
set -e

say() {
  echo "\e[33m=>\e[0m $@"
}

gem_install() {
  gem install $1 --no-document
}

require() {
  type $x >/dev/null 2>&1 || {
    echo >&2 "dotfiles: $x not installed."; exit 1;
  }
}

require 'rbenv'

say "Installing missing Ruby versions..."

versions=('2.0.0-p195' 'jruby-1.7.4')
installed=$(rbenv versions --bare)
gems=(gem-browse gem-ctags pry)

for version in $versions; do
  if [[ -z $installed[(r)$version] ]]; then
    rbenv install $version
  fi

  say "Installing global gems for $version..."
  RBENV_VERSION=$version rbenv exec gem i $gems >/dev/null
done
