#!/usr/bin/env bash
# Summary: Configure the shell environment for dotfiles
# Usage: eval "$(dotfiles init - [<shell>])"

set -e
[ -n "$DOTFILES_DEBUG" ] && set -x

print=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load dotfiles automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo 'eval "$(dotfiles init -)"'
    echo
  } >&2

  exit 1
fi

# mkdir -p "${DOTFILES_ROOT}/"{shims,versions}

# if [[ ":${PATH}:" != *:"${DOTFILES_ROOT}/shims":* ]]; then
#   echo 'export PATH="'${DOTFILES_ROOT}'/shims:${PATH}"'
# fi

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/dotfiles.${shell}\""
  ;;
esac

commands=(`dotfiles-commands --sh`)
IFS="|"
cat <<EOS
dotfiles() {
  typeset command
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in \${commands[*]})
    eval "\`dotfiles "sh-\$command" "\$@"\`";;
  *)
    command dotfiles "\$command" "\$@";;
  esac
}
EOS
