#!/usr/bin/env zsh
set -e

say() {
  echo "\e[33m=>\e[0m $@"
}

require() {
  type $x >/dev/null 2>&1 || {
    echo >&2 "dotfiles: $x not installed."; exit 1;
  }
}

require 'ghc'
require 'cabal'

# NOTE `cabal list --installed` doesn't include things like cabal-dev, which
# means we attempt to install it everytime you run dotfiles-haskell.
installed=($(cabal list --installed --simple-output | cut -d ' ' -f1))

cabal_install() {
  for dep in $@; do
    if [[ -z $installed[(r)$dep] ]]; then
      say "Installing $dep..."
      cabal install $dep >/dev/null
    fi
  done
}

say "Installing required Haskell support..."
cabal_install 'cabal-dev' 'goa' 'lambdabot'

say "Installing missing Haskell dependencies..."
cabal_install 'haxml' 'snap' 'yesod'
