---
- name: Install Haskell packages
  homebrew: name={{ item }} state=latest
  with_items:
    - cabal-install
    - gcc
    - ghc

- name: Update cabal
  shell: 'cabal update'
  tags: update

- name: Install packages
  shell: 'cabal install {{ dotfiles.haskell.packages | join(" ")}}'

- name: Link dotfiles
  file: src={{ item }} dest=~/.{{ item | basename }} state=link
  with_fileglob:
    - ./*
