---
- name: Enable GCC
  homebrew: gcc state=linked

- name: Install Haskell Platform
  homebrew: name=haskell-platform state=installed

- name: Install packages
  shell: 'cabal install {{ dotfiles.haskell.packages | join(" ")}}'

- name: Link dotfiles
  file: src={{ item }} dest=~/.{{ item | basename }} state=link
  with_fileglob:
    - ./*
