---
- name: Install plenv
  git: >-
    repo=git://github.com/tokuhirom/plenv.git
    dest=~/.plenv
  tags: update

- name: Clone plenv plugins
  git: >
    repo=git://github.com/{{ item }}.git
    dest=~/.plenv/plugins/{{ item | basename }}
  with_items:
    - tokuhirom/perl-build
  tags: update

- name: Install Perls
  command: plenv install {{ item }}
  with_items: dotfiles.perl.versions
  register: result
  failed_when: '".plenv/versions/{{ item }} is already installed" not in result.stderr'

- name: Install cpanm
  command: plenv install-cpanm
  environment:
    plenv_version: "{{ item }}"
  with_items: dotfiles.perl.versions
