---
- name: Install docker.py
  pip: name=docker-py state=latest
  tags: update

- name: Install packages
  homebrew: name={{ item }} state=latest
  with_items:
    - boot2docker
    - docker
    - docker-machine
  tags: update

- name: Find Docker machine
  command: docker-machine inspect dev
  register: machines

- name: Pull docker images
  docker: image={{ item }}
  when: machines.rc == 0
  with_items:
    - dockerfile/elasticsearch
    - dockerfile/redis
    - sylvainlasnier/memcached
