---
- name: Install Homebrew Cask
  homebrew: name=brew-cask state=latest
  tags: update

- name: Tap Cask versions
  homebrew_tap: tap=caskroom/versions state=present

- name: Install apps
  homebrew_cask: name={{ item }} state=installed
  with_items: dotfiles.apps or []
  tags: apps

- name: Show ~/Library
  shell: chflags nohidden ~/Library
  changed_when: no

- name: Set defaults
  shell: '{{ item }}'
  with_items: osx.defaults
  changed_when: no

- name: Restart Finder
  shell: killall Finder

- name: Restart Dock
  shell: killall Dock

- name: Install OSXFuse
  mac_pkg: >-
    pkg_version=2.7.5
    url=http://softlayer-ams.dl.sourceforge.net/project/osxfuse/osxfuse-2.7.5/osxfuse-2.7.5.dmg
    archive_type=dmg archive_path='Install OSXFUSE 2.7.pkg'
  sudo: yes
