export CURRENT_SHELL="bash"
export DOT_FILES=$(dirname $(dirname $(readlink $BASH_SOURCE)))

# All things that are both ZSH and Bash compatible
source $DOT_FILES/shell/common.sh

# RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
