export CURRENT_SHELL="bash"
export DOT_FILES=$(dirname $(dirname $(readlink $BASH_SOURCE)))

# All things that are both ZSH and Bash compatible
source $DOT_FILES/shell/common.sh
source $DOT_FILES/bash/rails_command.sh

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
