---
- name: Clone rbenv
  git: >
    repo=git://github.com/sstephenson/rbenv.git
    dest=~/.rbenv
  tags: update

- name: Clone ruby-build
  git: >
    repo=git://github.com/sstephenson/ruby-build.git
    dest=~/.rbenv/plugins/ruby-build
  tags: update

- name: Clone rbenv-ctags
  git: >
    repo=git://github.com/tpope/rbenv-ctags.git
    dest=~/.rbenv/plugins/rbenv-ctags
  tags: update

- name: Clone rbenv-readline
  git: >
    repo=git://github.com/tpope/rbenv-readline.git
    dest=~/.rbenv/plugins/rbenv-readline
  tags: update

- name: Clone rbenv-default-gems
  git: >
    repo=git://github.com/sstephenson/rbenv-default-gems.git
    dest=~/.rbenv/plugins/rbenv-default-gems
  tags: update

- name: Install Rubies
  shell: 'rbenv install --skip-existing {{ item }}'
  with_items: dotfiles.ruby.versions
  changed_when: no

- name: Set default Ruby version
  shell: 'rbenv global {{ dotfiles.ruby.default_version }}'

- name: Link dotfiles
  file: src={{ item }} dest=~/.{{ item | basename }} state=link
  with_fileglob:
    - ./*

- name: Link default gems
  template: src=default-gems dest=~/.rbenv/default-gems
